Resources:
  CatalogItemVersionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "CatalogItemVersions"
      AttributeDefinitions:
        - AttributeName: "bookId"
          AttributeType: "S"
        - AttributeName: "version"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "bookId"
          KeyType: "HASH"
        - AttributeName: "version"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST